### ISSUE TITLE
Small doc suggestion

### ISSUE THREAD

**Issue by tjdevries** [tamago324/lir.nvim#13]
Might want to mention in the README that by default there are no keymaps (at least, as far as I could tell) so when installing you're not surprised that nothing is happening :laughing: 

Cool plugin :) I like it thus far!

**Comment by tamago324** [comment]
Thank you for suggesting that!
Yes, it's probably a good idea to mention that you can't do anything without setting it up.
I've updated the README.md. What do you think?

> Cool plugin :) I like it thus far!

I'm very happy to hear you say that!

**Comment by tjdevries** [comment]
Yeah, that's perfect :) thanks for doing that.

One question -- what would be the easiest way for me to map `-` to open up lir in `%:h` of the current file? I liked that mapping from dirvish, which I am switching from.

**Comment by tamago324** [comment]
I've never used dirvish, so I don't know, but what about the following mapping?

```lua
lua vim.api.nvim_set_keymap(
    'n',
    '-',
    [[<Cmd>execute 'e ' .. expand('%:p:h')<CR>]],
    { noremap = true }
)
```

**Comment by kgnugur** [comment]
Hey, thank you for the plugin.
I too come from 'dirvish' what you suggested worked with one small issue. Is there a way to make it opened with the cursor under the current file? Instead of it being the top most. I want it to select the current file upon opening.

Thanks.

**Comment by tamago324** [comment]
@kgnugur Hi.
That was a bug and has been fixed. (4d6522fe64b95f123e82b59c791587cdccda6b91)
Could you try it?

Thank you for commenting here, even if you have a small question. Thanks to you, we were able to find the bug and fix it.

**Comment by kgnugur** [comment]
Hi,
Keybinding you have suggested to @tjdevries works alongside the new fix.
Thank you.

**Comment by tamago324** [comment]
@tjdevries May I close this?

**Comment by tamago324** [comment]
Close.
If you have any problems, please contact us.
