### ISSUE TITLE
Additional user configurable hl-groups

### ISSUE THREAD

**Issue by sunjon** [tamago324/lir.nvim#14]
Hi,

Could you please make the directory (and I guess symlink) hl-groups configurable?
The hl I have for the default FuncRef isn't very fitting.

Thanks!

**Comment by tamago324** [comment]
Thank you for your suggestion.
I have added the highlights.
Please try it out.

Please contact us if you have any further issues.

**Comment by sunjon** [comment]
Perfect! thanks
