### ISSUE TITLE
Close on lose focus

### ISSUE THREAD

**Issue by lucastrvsn** [tamago324/lir.nvim#16]
Hello!

I'm using this plugin and love it so far! But, I think is good to when I open the float and do `<C-w>h` (to back the focus to the opened file) the float window closes. Maybe it's a good idea to close it when loses focus?

Or just disable all others keymaps (like telescope do)?

https://user-images.githubusercontent.com/8826449/116765830-9c5b9600-a9fd-11eb-9f66-e9030ffd49cc.mov

Thanks!

**Comment by tamago324** [comment]
Hi.
Thank you for creating the issue.
Yes, it would be nice to have such a setting.

You can close the floating window when it loses focus by setting it as follows.

```lua
function _G.LirSettings()
  vim.cmd [[augroup LirCloseOnWinLeave]]
  vim.cmd [[  autocmd!]]
  vim.cmd [[  autocmd WinLeave <buffer> if get(w:, 'lir_is_float', v:false) | call nvim_win_close(0, v:true) | endif]]
  vim.cmd [[augroup END]]
end

vim.cmd [[augroup lir-settings]]
vim.cmd [[  autocmd!]]
vim.cmd [[  autocmd Filetype lir :lua LirSettings()]]
vim.cmd [[augroup END]]
```

**Comment by tamago324** [comment]
No reply, so I'll close it.
