### ISSUE TITLE
Duplicate tags in lir.jax 

### ISSUE THREAD

**Issue by ronniedroid** [tamago324/lir.nvim#17]
paq is complaining about there being duplicate tags in `lir.jax` and lir.txt file in docs directory.

**Comment by tamago324** [comment]
Thanks for the report.
I hadn't noticed the duplicate tags.
Please check it out as we have fixed it.

**Comment by ronniedroid** [comment]
Hey, the problem is fixed, sorry for the delayed reply.

**Comment by tamago324** [comment]
Thank you for checking :+1:
