### ISSUE TITLE
Make optional file opener callback function

### ISSUE THREAD

**Issue by sunjon** [tamago324/lir.nvim#19]
I'm thinking that if the user can supply a callback that's triggered on selection, what you do with it could be much more versatile, eg. Handing out certain filetypes to external programs.

**Comment by tamago324** [comment]
Thanks for the suggestion.

Sorry. Due to my lack of understanding, could you please tell me what specific program you are going to pass it to?
I could not visualize how to use it.

**Comment by sunjon** [comment]
xdg-open, or something similar that would do something based on the file/mimetype.

**Comment by tamago324** [comment]
I think it is possible to use a function to get the information of the target file.
Please let me know if I'm wrong, as I may have missed something.

```lua
require 'lir'.setup {
    -- ['l']     = actions.edit,
    ['l'] = function()
      local ctx = lir.get_context()
      local current = ctx:current()
      if string.match(current.value, '[^.]+$') == 'mp4' then
        vim.fn.system('xdg-open ' .. current.fullpath)
        return
      end
      actions.edit()
    end,

    --...
}
```

**Comment by sunjon** [comment]
yep, that's great.
Thanks!
