### ISSUE TITLE
Hide cursor bug

### ISSUE THREAD

**Issue by seblj** [tamago324/lir.nvim#20]
If I use the option to hide the cursor, the colors shift one character to the right making it look weird.

Here is the cursor enabled:
<img width="186" alt="image" src="https://user-images.githubusercontent.com/5160701/116901248-f8126300-ac39-11eb-8b59-28991fe0a5e1.png">

Here the cursor is hidden:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/5160701/116901311-0ceef680-ac3a-11eb-97c5-a6bfe146bc32.png">

**Comment by tamago324** [comment]
Thanks for reporting the problem.

It did not occur with my following minimum configuration.
Could you please try it?

```sh
$ nvim -u minvimrc -i NONE
```

```vim
set encoding=utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif
call plug#begin('~/.config/nvim/.plugged')
Plug 'tamago324/lir.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'kyazdani42/nvim-web-devicons'
call plug#end()

set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

if !has('gui_running')
  set termguicolors
endif

lua << EOF

local actions = require'lir.actions'

require'nvim-web-devicons'.setup({
  default = true,
  override = {
    ["lir_folder_icon"] = {
      icon = "",
      color = "#7ebae4",
      name = "FolderNode"
    },
  }
})

require 'lir'.setup {
  devicons_enable = true,
  hide_cursor = true
}

EOF
```

**Comment by seblj** [comment]
default = true fixed this for me in nvim-web-devicons.setup! Closing this now
