### ISSUE TITLE
Disable netrw

### ISSUE THREAD

**Issue by ofrades** [tamago324/lir.nvim#21]
In the terminal if I do `$ nvim /path/to/directory/` as the docs suggest, netrw opens instead of lir.
Do I need to configure something special or is a bug?

**Comment by ofrades** [comment]
This did the trick:
```
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
```

**Comment by tamago324** [comment]
Thank you for reporting the problem!
I've just added a FAQ to the doc.
