### ISSUE TITLE
Root dir is not loaded properly when accessing from `lir` buffer

### ISSUE THREAD

**Issue by dhruvmanila** [tamago324/lir.nvim#27]
I have the following action to go to the root dir similar to what you mentioned in the Wiki for going to the home dir:

```lua
    ["`"] = function()
      vim.cmd("edit /")
    end,
```

I tried using the above key binding from both the floating window and the split view and in both cases `lir` opened a blank buffer, although when I refreshed the buffer using `:edit`, then it shows me all the entries.

https://user-images.githubusercontent.com/67177269/119448620-3689d200-bd4f-11eb-9156-abf4938af85e.mov

I also tried doing `:edit /` from a normal buffer and that works perfectly. I don't know why this is happening.

**Comment by tamago324** [comment]
Thanks for the report.

I have also reported that issue to neovim. (https://github.com/neovim/neovim/issues/13726)
It is caused by the `BufEnter` event not happening.
Since I don't know the real cause of the problem, it seems that I have to run doautocmd BufEnter.

**Comment by tamago324** [comment]
Oh, so it only happens when you run it in the lir buffer?
I was mistaken.
I'll check it later.

**Comment by tamago324** [comment]
It may be that `vim.cmd('edit /')` is not working correctly.

**Comment by dhruvmanila** [comment]
> It may be that vim.cmd('edit /') is not working correctly.

Ah, yes this is the cause. I can confirm that the `BufEnter` autocmd is not being triggered in the case of `:lua vim.cmd('edit /')`, but is being triggered when doing the same with `:edit /`

With the workaround mentioned by you (manually triggering the autocmd) solves the issue.

If you want you can close this issue, or else could provide an instruction/warning regarding this type of behavior in the README.

**Comment by tamago324** [comment]
I added it to the docs. (29dbc6638b93b03577ca401e34fb3db2149ba063)
What do you think?

**Comment by dhruvmanila** [comment]
That's perfect 👍
