### ISSUE TITLE
Jump to the filename of the current buffer

### ISSUE THREAD

**Issue by kgnugur** [tamago324/lir.nvim#31]
Hi,
Opening lir with the cursor under the current file stopped working. A similar discussion was: https://github.com/tamago324/lir.nvim/issues/13#issuecomment-830762220

I think it has broken with an update.

**Comment by tamago324** [comment]
Thanks for the report!
It has been fixed. May I ask for your confirmation?

**Comment by kgnugur** [comment]
Yes it works now. Thank you.
