### ISSUE TITLE
First character of filename highlighted when devicons are enabled

### ISSUE THREAD

**Issue by The-personified-devil** [tamago324/lir.nvim#42]
When devicons are enabled, the first character of the filename is highlighted, due to the icon highlighting being applied at an offset of one space ([responsible code](https://github.com/tamago324/lir.nvim/blob/1dbb50f1084e3a2f63169d24e56e7f8ec16ec9f7/lua/lir/devicons.lua#L58)).
![image](https://user-images.githubusercontent.com/54042101/129449019-32a9687a-826c-4f41-8846-13639264f5cf.png)

**Comment by tamago324** [comment]
Thank you for your report.
Also, I am sorry for the delay in responding to you.
