### ISSUE TITLE
Folder icon doesn't appear correctly

### ISSUE THREAD

**Issue by ExtinctAxolotl** [tamago324/lir.nvim#48]
![image](https://user-images.githubusercontent.com/62254492/133898330-3747fa6f-d284-4297-b4a9-13359dd8132a.png)
In the above screenshot `src/` is a folder, but the icon doesn't show correctly.
My Configuration is copy and pasted from the README of lir.nvim.

**Comment by ExtinctAxolotl** [comment]
All other icons seem to appear correctly.

**Comment by ExtinctAxolotl** [comment]
Found a workaround when adding this to my packer config:
```lua
use { "kyazdani42/nvim-web-devicons", commit = "c8ce86df2ee0f5bb455c4188c8a4c77d3c9ef714" }

```

**Comment by tamago324** [comment]
It seemed that I needed to use `require'nvim-web-devicons'.set_icon(...)` instead of `require'nvim-web-devicons'.setup(...)`.
README.md is now fixed.
