### ISSUE TITLE
Getting error message after latest update 'Error detected while processing BufEnter Autocommands for "*":'

### ISSUE THREAD

**Issue by kgnugur** [tamago324/lir.nvim#50]
I started to get error when I enter lir, I can proceed to use it but error pops out every time I use lir.nvim.

Here is the message:
```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...l/share/nvim/site/pack/packer/start/lir.nvim/lua/lir.lua:243: Vim(lua):E5108: Error executing lua ...ck/packer
/start/lir.nvim/lua/lir/float/curdir_window.lua:113: attempt to index field 'curdir_window' (a nil value)
```

Thank you.

**Comment by kgnugur** [comment]
Hi, I had `float = {}` in my `require'lir'.setup { }`  after deleting that line `lir`started working againg.

I was using commit `commit = '5a7b21b0fdafe73719902b9848880fb3eb8500aa'` in the meanwhile. Sorry for not communicating with you I was very busy.

**Comment by tamago324** [comment]
Thanks for the info!
We have just corrected the problem.

Don't worry, I can be slow to reply too.
