### ISSUE TITLE
FYI on dirvish/netrw style `nvim ./`

### ISSUE THREAD

**Issue by pard68** [tamago324/lir.nvim#51]
If lir.nvim is loaded within the `vim.defer_fn()` than dirvish/netrw style loading will not work properly. I do not know why this is, but just wanted to make you aware. I do not know if this is something that can be fixed or if the answer is to either avoid `defer_fn` entirely or to just be aware that if you use it you'll need to than call `lir` outside of it.

**Comment by pard68** [comment]
I'm closing this issue. I swapped to packer from paq and I can now use the fn_defer and the other issues are all gone as well. I'm going to assume it was something to do with how packadd was being called...?

**Comment by tamago324** [comment]
I don't know the cause, but I'm glad it seems to have been resolved anyway.
Thank you for the report.
