### ISSUE TITLE
Float fails when in Terminal buffer

### ISSUE THREAD

**Issue by pard68** [tamago324/lir.nvim#52]
To reproduce:
1. `:terminal<cr>`
2. `:lua require'lir.float'.toggle()`
3. The opposite of profit

As best as I can tell, if you toggle a floating Lir window while in a terminal buffer, Lir will fail with the error

```sh
...lir/float/curdir_window.lua:98: attempt to index a ni value
```

In addition to this error in the command area, it shows `Process exited 0` in the floating window. Upon exiting this window `:q` the "heading" window (smaller floating window above the larger floating window) remains up and will not go away until Neovim is exitted.

I discovered another issue that I cannot replicate but I believe might be tied to the above issue nonetheless:

Sometimes a buffer of Lir seems to "hang" in the background. For some reason this buffer cannot be killed and `:q` will not quit, due to this buffer being open. The only way to escape from this Neovim-jail is with a `:quitall`. There is a chance that this is unrelated to Lir, however it seems to only ever happen following the above error.

**Comment by tamago324** [comment]
Thanks for the report! Fixed.
Please check it out.
