### ISSUE TITLE
guicursor not restored to custom setting when hide_cursor is enabled

### ISSUE THREAD

**Issue by creativenull** [tamago324/lir.nvim#53]
If I have manually set `guicursor` to something other than the default provided and have `hide_cursor` enabled in lir then after opening lir a file in lir will reset it back to the nvim provided default and not the user provided option.

Steps to reproduce:

1. `set guicursor=n-v-c-sm:block,i-ci-ve:block,r-cr-o:hor20`
2. Add `hide_cursor` to lir setup `require('lir').setup({ hide_cursor = true })`
3. Open a lir instance with `:lua require('lir.float').toggle()`
4. Choose a file to open
6. Check `guicursor` with `:set guicursor?`

---

Expected Result

`guicursor` should be the same as set in Step 1

Actual Result

`guicursor` is set to default nvim `guicursor` setting: `n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20`

---

I have a fork with the [proper changes needed for it to persist user configured option](https://github.com/creativenull/lir.nvim/commit/a6c51787a401c20c058f70114e3df7a298877741) with `hide_cursor` enabled and be will to make the PR. But I wanted to see if it is an issue with other users as well before I can proceed.

**Comment by tamago324** [comment]
Thank you for reporting the bug and describing how to reproduce it in detail!
I was able to reproduce the bug.

I've tried the repository you forked (fix-guicursor branch) and it looks like the bug is fixed.
If you can, please create a PR for it.

Thanks for your contribution!
