### ISSUE TITLE
Don't show files set in `wildignore`

### ISSUE THREAD

**Issue by Murderlon** [tamago324/lir.nvim#60]
Similar to netrw it would be nice to filter out files defined in `wildignore`. For instance, I never want to see `.DS_Store`.

I'm open to creating a PR for it if you give me some pointers.

**Comment by tamago324** [comment]
Can you be more specific?
What features would you like to see?

**Comment by Murderlon** [comment]
When using the default directory and file navigator (netrw) of (n)vim, adding a file (such as `.DS_Store`) to [`wildignore`](https://vimhelp.org/options.txt.html#%27wildignore%27) will cause the file to not be shown in the file tree. I thought it might be interesting to align with netrw on this.
