### ISSUE TITLE
Add LirCursorLine hightlight

### ISSUE THREAD

**Issue by PongPong** [tamago324/lir.nvim#63]
As the current float window use CursorLine hightlight for selection, May I request adding a LirCursorLine highlight group.

e.g `set hi link LirCursorLine Visual`

**Comment by tamago324** [comment]
Do you want to set the highlight only for the Float window?
Or do you want to set the highlight also for the normal buffer that is displayed when `:e .` is executed?

**Comment by PongPong** [comment]
for the file explorer only , whatever it is floating window/project drawer/ full screen mode.
I am not sure about the later one, could you elaborate? 
normal buffer should not be affected even the LirCursorLine highlight is on the global scope.

**Comment by tamago324** [comment]
There are two ways to open lir.nvim.
1. by opening `:e.` If you want to display it in a normal buffer like netrw
2. `:lua require('lir.float').init()` to display in a floating window.

I plan to define `LirFloatCursorLine` and implement a way to change the highlight of the cursor line only in case 2.

I think you are right, and it can be set with `nvim_set_option()` without affecting other windows.

**Comment by tamago324** [comment]
Implementation.
If you would like to give it a try, please do so.

**Comment by PongPong** [comment]
Thanks for helping, I love your implementation , I 've just migrated from my nvim-tree config.

**Comment by tamago324** [comment]
Merged.
Thanks for the suggestion!
