### ISSUE TITLE
Some issues with README

### ISSUE THREAD

**Issue by ishan9299** [tamago324/lir.nvim#9]
I don't think the Screenshots are actually present in the images repo. I tried to download them but it didn't happen.

Also in lir setup if the if I comment out the this portion :-
```
  float = {
    size_percentage = 0.5,
    winblend = 15,
    border = true,
    borderchars = {"╔" , "═" , "╗" , "║" , "╝" , "═" , "╚", "║"},
    shadow = true,
  },
```
I am able to see the window borders. If these are not commented out I can't see the borders. 

I think it is kind of difficult to figure out how to open a non-floating window.

**Comment by tamago324** [comment]
Thank you for reporting the issue.
The following is my response.

> I don't think the Screenshots are actually present in the images repo. I tried to download them but it didn't happen.

A screenshot is available at [tamago324/images](https://github.com/tamago324/images/tree/master/lir.nvim).

> Also in lir setup if the if I comment out the this portion :-
> ...

Sorry about the settings, the example in README.md was not correct.
I will fix it.

> I think it is kind of difficult to figure out how to open a non-floating window.

By `non-floating window`, do you mean opening lir.nvim with a normal buffer?
If so, you can use commands like `:edit .` and `:edit %:p:h` to open it.


I am not familiar with English, so I would appreciate it if you could tell me if I am reading something wrong.

**Comment by tamago324** [comment]
README.md has been fixed. dc57782a80ec163414e43c3548fe686d0c46974a
If `shadow` is set to `true`, the value of `borderchars` will be ignored.

**Comment by ishan9299** [comment]
![Screenshot from 2021-04-29 19-00-45](https://user-images.githubusercontent.com/47824004/116558688-54654200-a91d-11eb-9324-95d8c7f9a807.png)
This is how it looks on my laptop but I was able to see the screenshots in the github mobile lab.

**Comment by tamago324** [comment]
@ishan9299 It was displaying correctly from my browser, so I assumed it was fine.
I have created a PR (#11) , could you please check it if possible?
